### ISSUE TITLE
SKU search # 122

### ISSUE THREAD

**Issue by SiddiqueAhmad** [EsajeeSolutions/Esajeesite#1]
Search using the SKU ID returns no results. We need this to work like it does on the current live site

**Comment by sabzesajee** [comment]
Fixed and updated on live

**Comment by sabzesajee** [comment]
@SiddiqueAhmad Fixed

**Comment by kamrannaqvi** [comment]
Verified fixed.

**Comment by uuaqarahmed** [comment]
closed
