### ISSUE TITLE
Update order status  # 99

### ISSUE THREAD

**Issue by SiddiqueAhmad** [EsajeeSolutions/Esajeesite#12]
order status updates in magento, order should be confirmed so customer can get email that his order is ready to be picked up

**Comment by sabzesajee** [comment]
Not required

**Comment by kamrannaqvi** [comment]
@sabzesajee Pls. explain your comment. The feature to send customer an order confirmation message (telling them to pickup the order within 12 hours) is required. It is different from order acknowledgement email which is sent as soon as the order is placed online, whereas the confirmation message is sent once the order is packed and is ready for pickup from the store.

**Comment by uuaqarahmed** [comment]
@kamrannaqvi I believe this should be served with order confirmation as in #20

**Comment by kamrannaqvi** [comment]
@uuaqarahmed Correct.
