### ISSUE TITLE
more categories in the main menu #29

### ISSUE THREAD

**Issue by uuaqarahmed** [EsajeeSolutions/Esajeesite#13]
![image](https://cloud.githubusercontent.com/assets/527591/5997893/e74d5b88-aae2-11e4-91b7-e793a5225609.png)

Comment:

![image](https://cloud.githubusercontent.com/assets/527591/5997901/0066cd98-aae3-11e4-9af1-d53109e1cdfe.png)

**Comment by sabzesajee** [comment]
link added at the end for view all categories

**Comment by kamrannaqvi** [comment]
The menu is is not balanced (the bottom of the menu should align with the bottom of the adjacent carousel). The "circle" icon is also not there for last 2 menus.

**Comment by kamrannaqvi** [comment]
Resolved.
