### ISSUE TITLE
New payment method "self pickup" #41

### ISSUE THREAD

**Issue by uuaqarahmed** [EsajeeSolutions/Esajeesite#14]
![image](https://cloud.githubusercontent.com/assets/527591/5997922/35c2de50-aae3-11e4-82f0-4e0b169a8506.png)

**Comment by sabzesajee** [comment]
fixed

**Comment by kamrannaqvi** [comment]
Checkout not working. Also this needs to implement details, listed as #65, 66:
![image](https://cloud.githubusercontent.com/assets/10416359/6101581/43acf554-b048-11e4-9064-302a09eccf3b.png)

**Comment by uuaqarahmed** [comment]
@kamrannaqvi  just to clarify, this is not adding item in the cart instead it will happen after checkout

@sabzesajee duplicate of #19
