### ISSUE TITLE
advance search not stable #77

### ISSUE THREAD

**Issue by uuaqarahmed** [EsajeeSolutions/Esajeesite#17]
![image](https://cloud.githubusercontent.com/assets/527591/5997984/f67762e2-aae3-11e4-9b4d-519aae7ec9b5.png)

**Comment by sabzesajee** [comment]
fixed

**Comment by uuaqarahmed** [comment]
@kamrannaqvi  please test and verify

**Comment by kamrannaqvi** [comment]
resolved.
