### ISSUE TITLE
incorrect shipping method total #84

### ISSUE THREAD

**Issue by uuaqarahmed** [EsajeeSolutions/Esajeesite#18]
![image](https://cloud.githubusercontent.com/assets/527591/5997994/16f608f2-aae4-11e4-983f-76bd1b1bdae5.png)

**Comment by sabzesajee** [comment]
fixed

**Comment by kamrannaqvi** [comment]
All info is removed. This can be closed after #117 is implemented.

**Comment by kamrannaqvi** [comment]
Resolved.
