### ISSUE TITLE
order emails #94

### ISSUE THREAD

**Issue by uuaqarahmed** [EsajeeSolutions/Esajeesite#19]
![image](https://cloud.githubusercontent.com/assets/527591/5998028/5fd7c93e-aae4-11e4-8055-caa4e27edfba.png)

**Comment by sabzesajee** [comment]
@kamrannaqvi  Already fixed. On order placed two emails are generated one to customer and the other two stop.
The stop email address can be change from back end configuration in store email address in online order tab

**Comment by kamrannaqvi** [comment]
Could not be verified. The checkout feature is not working now.

**Comment by uuaqarahmed** [comment]
@sabzesajee please update after applying email templates ..

**Comment by sabzesajee** [comment]
@kamrannaqvi  You Can check email format of 1(a),1(b),2(b)
The checkout process is working now

**Comment by kamrannaqvi** [comment]
Email format for 1a and 1b is do not match the templates (Discuss with Hussnain). Also pls. mention the step to test 2b email.

**Comment by sabzesajee** [comment]
check emails templates now. 
For 2b check the screens shot.
![step1](https://cloud.githubusercontent.com/assets/6996232/6162506/4af157aa-b2a6-11e4-92c5-0dd5f683a3e3.jpg)
![step2](https://cloud.githubusercontent.com/assets/6996232/6162509/543e0ae2-b2a6-11e4-9e7a-cb0529e7a1d1.jpg)

**Comment by kamrannaqvi** [comment]
verified.
