### ISSUE TITLE
Search by brand # 125

### ISSUE THREAD

**Issue by SiddiqueAhmad** [EsajeeSolutions/Esajeesite#2]
Searching using brand filter does not generally work. No search criteria produce any results when we search "By Brand". This may be because the products can not be assigned a brand any more (as reported in issue # 121). Even the products that were previously assigned a brand have been found unassigned.

**Comment by sabzesajee** [comment]
@SiddiqueAhmad  issue # 125 Fixed

**Comment by kamrannaqvi** [comment]
Can be verified only after latest data is imported from live magento, where all skus are assigned to brands.

**Comment by kamrannaqvi** [comment]
resolved.
