### ISSUE TITLE
stock management after store pickup #97

### ISSUE THREAD

**Issue by uuaqarahmed** [EsajeeSolutions/Esajeesite#21]
![image](https://cloud.githubusercontent.com/assets/527591/5998050/c850577e-aae4-11e4-927a-8c27af4c8aef.png)

**Comment by uuaqarahmed** [comment]
1. magento should update its stock (already doing)
2. pos will update on payment confirmation (already doing)
3. order cancellation should revert units back in magento

Question: @SiddiqueAhmad How will stock be adjusted for sales in POS?

**Comment by SiddiqueAhmad** [comment]
if we not change the magento stock on order confirmation, we can do this via sync pos to magento

**Comment by uuaqarahmed** [comment]
@sabzesajee  please add test instructions

**Comment by sabzesajee** [comment]
this will sync from pos side

**Comment by uuaqarahmed** [comment]
already working
