### ISSUE TITLE
checkout changes #117

### ISSUE THREAD

**Issue by uuaqarahmed** [EsajeeSolutions/Esajeesite#23]
![image](https://cloud.githubusercontent.com/assets/527591/5998120/ab3998b6-aae5-11e4-87c8-308799c20055.png)

**Comment by sabzesajee** [comment]
For multiple store select list: As we already have given an option to select store on top of the page and in pop up window when first time a user come to the site. then if a user want to order a product then automatically it will place order from selected store.

**Comment by kamrannaqvi** [comment]
As marked above, 1b and 1c are deferred. So for point #1 pls. work on 1a and 1d only for now.

**Comment by sabzesajee** [comment]
@kamrannaqvi  all fixed please check

**Comment by kamrannaqvi** [comment]
@sabzesajee please remove extra line spacing in some boxes and the content in the first step needs to be aligned properly. Discuss with Hussnain for clarification.

**Comment by kamrannaqvi** [comment]
verified.
