### ISSUE TITLE
cms pages left menu format #119

### ISSUE THREAD

**Issue by uuaqarahmed** [EsajeeSolutions/Esajeesite#24]
![image](https://cloud.githubusercontent.com/assets/527591/5998131/d020e832-aae5-11e4-9369-33328394175e.png)

**Comment by sabzesajee** [comment]
already told Hussnain how to set this.

**Comment by kamrannaqvi** [comment]
This is about the design of the 3 pages  which were listed. The design should match the Terms & Conditions page.

**Comment by sabzesajee** [comment]
Done. Check now

**Comment by kamrannaqvi** [comment]
Resolved.
