### ISSUE TITLE
search by brand no results #124

### ISSUE THREAD

**Issue by uuaqarahmed** [EsajeeSolutions/Esajeesite#27]
![image](https://cloud.githubusercontent.com/assets/527591/5998191/7f0f5ee6-aae6-11e4-8e55-28f5b0afd7d9.png)

**Comment by sabzesajee** [comment]
i have fixed this and it is working. need to add brand from back end with products. If still facing issue in testing then tell me i will guide.

**Comment by kamrannaqvi** [comment]
Can be closed after new data is imported and this is retested.

**Comment by kamrannaqvi** [comment]
resolved.
