### ISSUE TITLE
POS transaction # in bill #134

### ISSUE THREAD

**Issue by uuaqarahmed** [EsajeeSolutions/Esajeesite#28]
![image](https://cloud.githubusercontent.com/assets/527591/5998203/9bdc0a06-aae6-11e4-98e9-f7493f2a93ed.png)

**Comment by sabzesajee** [comment]
Not related to me

**Comment by uuaqarahmed** [comment]
@sabzesajee 

We have to provide facility in orders management to save transaction number. This should be one custom field that is filled by the staff during order confirmation

**Comment by sabzesajee** [comment]
Bill Add option added at backend order form.
How to add, Follow these steps:
1. go sales>order
2. edit any order and check for bill number
3. add bill number in the text field and click on submit bill button to save.

**Comment by uuaqarahmed** [comment]
@kamrannaqvi  please test this.

**Comment by kamrannaqvi** [comment]
Verified working -for existing orders in the backend. Could not test by creating new order because the checkout function is not working on the frontend.

**Comment by kamrannaqvi** [comment]
verified.
