### ISSUE TITLE
right click issue # 126

### ISSUE THREAD

**Issue by SiddiqueAhmad** [EsajeeSolutions/Esajeesite#3]
When I right click on Quick View of a product, the product page does not opens up correctly. (Screen Shot, attached)
![126](https://cloud.githubusercontent.com/assets/6996232/5812922/0c8bf42e-a096-11e4-9b2f-2cee801b900a.jpg)

**Comment by sabzesajee** [comment]
@SiddiqueAhmad   This is not a bug as Quick view is only for pop.

**Comment by uuaqarahmed** [comment]
not an issue.
