### ISSUE TITLE
stock update mechanism

### ISSUE THREAD

**Issue by uuaqarahmed** [EsajeeSolutions/Esajeesite#34]
@SiddiqueAhmad Before any further work is done on this issue, please answer "Should there be an update mechanism at magento end?"

I have come across an issue i.e.

> When I placed an order for a product at esajee's website, the stock at backend did updated from Qty of 19 to Qty of 18.

> Then, I sent the Confirmation email from magento backend to the customer that please pick your order from store within 12 hours etc.

> Assume, the customer did not showed up in 12 hours time, so, the store staff needs to send the CANCELLATION email to the client and has to put the products back to shelves, that means the STOCK should be updated, and quantity should increase i.e. products have been returned to shelves and is not sold, so that pruct should show quantity of 19 now, but, it did not updated. (After cancellation of the order, the quantity remains same as 18).

![after order placed confirmed](https://cloud.githubusercontent.com/assets/527591/6243904/4a46dcbe-b76d-11e4-8761-d65f134320c1.jpg)
![before placement of order](https://cloud.githubusercontent.com/assets/527591/6243905/4a4d7c4a-b76d-11e4-808e-beb33b4c614b.jpg)
![after order cancelled no update in stock](https://cloud.githubusercontent.com/assets/527591/6243906/4b1e84f2-b76d-11e4-936e-44d9c950a3dd.jpg)

**Comment by SiddiqueAhmad** [comment]
we decided last time, it should not update stocks from magento side, so issue is on order booking, @sabzesajee it should not minus the qty
