### ISSUE TITLE
Checkout when creating new user is not normal

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#35]
a. When a new customer checks out -> creates account -> next step -> "Self pickup store" box shows the signup form instead of the usual content.

b. Also, all customer signup form fields must be moved to the first step when a new customer creates his user account.

![image](https://cloud.githubusercontent.com/assets/10416359/6281664/ffa81e5e-b8e6-11e4-8046-438378ad3873.png)

**Comment by uuaqarahmed** [comment]
@kamrannaqvi 

The form appears because address information is necessary for customer to signup. Removing address information at this stage would require a lot of changes. An alternative is to take address input from the customer at account creation stage.

**Comment by sabzesajee** [comment]
@kamrannaqvi  
Customer Address information fields are enable on customer registration form so this will remove the issue.

**Comment by kamrannaqvi** [comment]
Resolved.
