### ISSUE TITLE
Checkout item quantity bug

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#36]
The Quantity (Qty) on test magento front end, is seen 0 by default for every product. Which is not correct.

When 0 qty product is added to cart for purchase, the QTy at that checkout turns 1 from 0.
Whatever quantity we enter before clicking "Add to Cart" it is incremented by 1 on the checkout page.

![when i open a random product quantity shown as 0](https://cloud.githubusercontent.com/assets/10416359/6281966/0af05266-b8ee-11e4-868e-22102337520a.jpg)
![when proceed to checkout cart 0 qty turns to 1 qty](https://cloud.githubusercontent.com/assets/10416359/6281967/0af1b0d4-b8ee-11e4-956c-028f7ac2ae80.jpg)

**Comment by sabzesajee** [comment]
Fixed

**Comment by kamrannaqvi** [comment]
Verified.
