### ISSUE TITLE
Stocks not updated on Sales #140

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#39]
![image](https://cloud.githubusercontent.com/assets/10416359/6408010/d85ae408-be6d-11e4-96e2-3e0b82370ce3.png)

**Comment by uuaqarahmed** [comment]
This involves 2 steps:

1. adjustment 
2. sale

**Comment by uuaqarahmed** [comment]
working, tested by Farooq sb
