### ISSUE TITLE
Brand logos # 127

### ISSUE THREAD

**Issue by SiddiqueAhmad** [EsajeeSolutions/Esajeesite#4]
Logos at end of the Page i.e. Hershey's, Cadbury, Airheads etc
When I click on them, they route me to search and it says ""No items were found"" etc. This was fine before

**Comment by sabzesajee** [comment]
Need to assign products to these brands from backend

**Comment by uuaqarahmed** [comment]
Please mention the process and train hussnain

**Comment by kamrannaqvi** [comment]
Will retest after latest data is imported from live magento, where all skus are assigned to brands.

**Comment by uuaqarahmed** [comment]
@sabzesajee 

Please import data from live to test

**Comment by SiddiqueAhmad** [comment]
@sabzesajee if you need any of my help, let me know

**Comment by kamrannaqvi** [comment]
resolved.
