### ISSUE TITLE
Most Barcodes mismatch in Magento vs. SCM/POS #137

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#42]
![image](https://cloud.githubusercontent.com/assets/10416359/6408057/8a5162fe-be6e-11e4-9189-ca11d1004760.png)

**Comment by uuaqarahmed** [comment]
Please mention a few examples

**Comment by kamrannaqvi** [comment]
27000378823, 41580102005, 27000380086, 64144282432, 37100042135, and so on. There are many many more.

**Comment by uuaqarahmed** [comment]
Thanks, we will figure this out.

**Comment by uuaqarahmed** [comment]
fixed

**Comment by kamrannaqvi** [comment]
Verified.
