### ISSUE TITLE
No image comes up in the quick view mode #143

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#45]
Some SKUs show image in showcase and also inside their detail page but no image comes up in the quick view mode. Then there are SKUs that show images in showcase and the quick view mode but no image is displayed when SKU details page is opened.
![143](https://cloud.githubusercontent.com/assets/10416359/6551808/08da63f2-c660-11e4-8642-9507d18ac0cf.png)

**Comment by uuaqarahmed** [comment]
This has been fixed, please check again

**Comment by kamrannaqvi** [comment]
Fixed.
