### ISSUE TITLE
Remove the phrase (Click on above image to view full picture) #144

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#46]
Remove the phrase (Click on above image to view full picture) from the Quick View of all items, as it is not aligned and also clicking on "above" picture does not work
![144](https://cloud.githubusercontent.com/assets/10416359/6551848/b305a602-c660-11e4-82e5-2f1591e67d20.png)

**Comment by sabzesajee** [comment]
Done

**Comment by kamrannaqvi** [comment]
verified.
