### ISSUE TITLE
All Categories Tab next to Search is miss-aligned #145

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#47]
All Categories Tab next to Search is miss-aligned. This needs to be vertically in middle of the box.
![145](https://cloud.githubusercontent.com/assets/10416359/6551862/d9970928-c660-11e4-9884-984eee9cc994.png)

**Comment by sabzesajee** [comment]
Fixed

**Comment by kamrannaqvi** [comment]
verified.

**Comment by uuaqarahmed** [comment]
check

**Comment by kamrannaqvi** [comment]
fixed.
