### ISSUE TITLE
Main page shows half images and empty space in the last slider slot #146

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#48]
‘On Sale’ and ‘Most Viewed’ product showcase vertical slider has an issue that it shows half images. Also shows empty space in the last slot (see attached). The issue is not consistent and next time when reloads it might work fine. This happens in multiple browsers as well
![146](https://cloud.githubusercontent.com/assets/10416359/6551874/030f9cb6-c661-11e4-9001-e6945e66c030.jpg)

**Comment by uuaqarahmed** [comment]
@kamrannaqvi fixed check

**Comment by kamrannaqvi** [comment]
verified.
