### ISSUE TITLE
Add to cart issue # 128

### ISSUE THREAD

**Issue by SiddiqueAhmad** [EsajeeSolutions/Esajeesite#5]
Ordering of Ben & Jerry Ice Cream (http://esajeecom.esajee.com/quickstart/index.php/ice-cream-chocolate-fudge-brownie-froyo-473ml-ben-and-jerry.html), when I click Add to Cart it gives the same error as reported in #131. See attached.

![131](https://cloud.githubusercontent.com/assets/6996232/5812985/3f926c80-a097-11e4-9a81-9995833f71f3.jpg)

**Comment by sabzesajee** [comment]
@SiddiqueAhmad Fixed and updated on live

**Comment by uuaqarahmed** [comment]
Still showing error on live, screenshot attached:

![untitled](https://cloud.githubusercontent.com/assets/527591/5850984/eb51b5b4-a220-11e4-8f9c-8eabc402d43b.png)

**Comment by sabzesajee** [comment]
Now Fixed.. All products recurring profile set to "No" from "Yes" by running scrip

**Comment by kamrannaqvi** [comment]
verified fixed.

**Comment by uuaqarahmed** [comment]
closed
