### ISSUE TITLE
Tags with 0.00 are still visible #148

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#50]
Unrealistic Price Tags Products are visible. Tags with 0.00 are still visible, for In stock items.
![148](https://cloud.githubusercontent.com/assets/10416359/6551927/99fd52c6-c661-11e4-85d4-b372533edb9a.jpg)

**Comment by uuaqarahmed** [comment]
@SiddiqueAhmad is this dependent on stock taking?

**Comment by sabzesajee** [comment]
this comes from live esajee.com which have no price

**Comment by sabzesajee** [comment]
some of the products on live site have 0 price

**Comment by kamrannaqvi** [comment]
The live site do not display prices at all so this does not cause any issues, but for the new site we need to hide products with 0 prices until the prices are entered in backend by SCM/staff, even when such products are "enabled". Lets discuss possible solutions

**Comment by sabzesajee** [comment]
all product having price 0 updated to out of stock to hide the front end display.

now by updating from SCM these will then show on front

**Comment by uuaqarahmed** [comment]
@sabzesajee only items with image will be activated?

**Comment by uuaqarahmed** [comment]
@kamrannaqvi enabled items will be updated and made visible when price is updated from scm

**Comment by kamrannaqvi** [comment]
ok. But there are still many products visible with 0 price tag and status as In stock. 
E.g. 040000011019, 088300105304, 099482406578, 022000126122

**Comment by kamrannaqvi** [comment]
brut resolved.
