### ISSUE TITLE
In Advanced Search, the S of sale needs to be capitalized #149

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#51]
In Advanced Search, "Sale" list is available, pls. the S of sale needs to be capitalized.

![149](https://cloud.githubusercontent.com/assets/10416359/6551933/be54bb1e-c661-11e4-8771-8694e9dd38fc.png)

**Comment by sabzesajee** [comment]
Set this from backend. go to attributes and change title

**Comment by kamrannaqvi** [comment]
verified.
