### ISSUE TITLE
Special Order > No feedback to user after clicking Save #151

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#53]
Special Orders (Clicking SAVE after inputting all content) > After clicking on SAVE button, the page reloads, but there is no feedback and comes back on the same form. There needs to be a confirmation message once the info is submitted by the user (Your Special Order has been recieved and will be processed shortly. You will be contacted by our store for any further action. Thank you for shopping at Esajee's)

**Comment by sabzesajee** [comment]
Done

**Comment by uuaqarahmed** [comment]
@sabzesajee 

After saving special order information, it shows following error message:

Exception printing is disabled by default for security reasons.

Error log record number: 601810899274

**Comment by sabzesajee** [comment]
Fixed

**Comment by kamrannaqvi** [comment]
verified.
