### ISSUE TITLE
Special Order > table alignment issue #152

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#54]
The special orders list is not aligned properly and the table cell lines go beyond the table boundries. See attached.
![155](https://cloud.githubusercontent.com/assets/10416359/6551969/31193c92-c662-11e4-8572-c651971b7acd.png)

**Comment by uuaqarahmed** [comment]
@sabzesajee please trim the visible URL

**Comment by sabzesajee** [comment]
fixed

**Comment by kamrannaqvi** [comment]
verified.
