### ISSUE TITLE
Special Order Emails need to be properly formatted #153

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#55]
After Placing an Special Order Emails are received, but those need to be properly formatted, they are not aligned etc. 
![156](https://cloud.githubusercontent.com/assets/10416359/6551982/58979020-c662-11e4-8a03-68c0ca02d95c.jpg)

**Comment by sabzesajee** [comment]
@kamrannaqvi  Please attach your required format

**Comment by kamrannaqvi** [comment]
Please discuss with Hussnain

**Comment by kamrannaqvi** [comment]
@sabzesajee 
![image](https://cloud.githubusercontent.com/assets/10416359/6633768/8e4c2900-c96f-11e4-9277-fa8784bb0c09.png)

**Comment by sabzesajee** [comment]
check now

**Comment by kamrannaqvi** [comment]
verified.
