### ISSUE TITLE
Products without showcase image are listed #154

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#56]
There are many products which are without their IMAGES. They are blank in image box in showcase.
Example:
http://esajeecom.esajee.com/quickstart/index.php/candy-and-chocolate/gum-and-mints.html?alias=gum-and-mints
![157](https://cloud.githubusercontent.com/assets/10416359/6552008/ad92ed2c-c662-11e4-9307-9ff8873b8bea.jpg)

**Comment by uuaqarahmed** [comment]
fixed, please test

**Comment by kamrannaqvi** [comment]
Still several items found without images. Linked to new issue #65
