### ISSUE TITLE
3 categories are empty #156-158

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#58]
![image](https://cloud.githubusercontent.com/assets/10416359/6552036/eb2442bc-c662-11e4-95f8-7b4c40a0f7c5.png)

**Comment by sabzesajee** [comment]
Fixed

**Comment by kamrannaqvi** [comment]
Found an empty category, which was fine before: 
http://esajeecom.esajee.com/quickstart/index.php/cooking-and-baking/whipping-cream.html

**Comment by sabzesajee** [comment]
If you check the sku that you have sent in excel sheet for the whipping cream these all are in cooking oil category on live site.
