### ISSUE TITLE
Banner image issues #159

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#59]
The Banner immage on the main page is not behaving normal:
1. May not load at all
2. If it shows up, the progress bar (showing the image is still loading) in middle of the image keeps showing as well
3. Zooms too much in to the image showing broken pixels of even very high res images
![162](https://cloud.githubusercontent.com/assets/10416359/6552050/0a1d850c-c663-11e4-9d7d-ecef7f817815.png)

**Comment by sabzesajee** [comment]
Fixed

**Comment by uuaqarahmed** [comment]
@kamrannaqvi The 3rd issue can be avoided by attaching only those products that have fine quality images having width x height of 500x370 or close

**Comment by kamrannaqvi** [comment]
The current banner looks distorted with large black strips, which makes the image crumble. Please fix.

**Comment by uuaqarahmed** [comment]
@kamrannaqvi its the image issue
