### ISSUE TITLE
Add to cart error # 131

### ISSUE THREAD

**Issue by SiddiqueAhmad** [EsajeeSolutions/Esajeesite#6]
If I add more quantity of a same product to cart, while shopping, it gives a error, and does not add it. (Screen Shot Attached) It only gives this error if I have already selected some other products for shopping and added in cart already. This occurred twice, but then it didn't. Please trace the error in your logs

![131](https://cloud.githubusercontent.com/assets/6996232/5812974/24de4e86-a097-11e4-8c2a-789225024604.jpg)

**Comment by sabzesajee** [comment]
@SiddiqueAhmad  fixed

**Comment by kamrannaqvi** [comment]
verified fixed.

**Comment by uuaqarahmed** [comment]
closed
