### ISSUE TITLE
Christmas Carousel images issue #160

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#60]
Christmas Carousel images are cut in half and the names of items are not showing up. This problem occurs erratically
![163](https://cloud.githubusercontent.com/assets/10416359/6552059/243b9e10-c663-11e4-9b6b-69aa0c8a096e.png)

**Comment by uuaqarahmed** [comment]
@kamrannaqvi couldn't reproduce this, can you check again and list down the steps you followed when this occured

**Comment by kamrannaqvi** [comment]
1. opened the home page
2. refreshed few times (both normal and with Ctrl). All fine
3. logged in as a customer
4. Pressed ctrl+F5 and the problem appeared again
5. Again, even this procedure is random

**Comment by uuaqarahmed** [comment]
@sabzesajee please set value of height:92px;width:92px; in .jm-slider li img  in the /skin/frontend/default/jm_megamall/joomlart/jmproductsslider/css/style.css file

**Comment by sabzesajee** [comment]
updated @kamrannaqvi  check please

**Comment by kamrannaqvi** [comment]
The images now show completely even though the issue is not resolved, but now the item name that used to display under each item image is not showing (same random appearing/disappearing nature). See shot below:

![image](https://cloud.githubusercontent.com/assets/10416359/7223560/f4854702-e73c-11e4-9fe7-182b26fda760.png)

**Comment by sabzesajee** [comment]
on first load its take some seconds to load css.

when i opened the page then names were not displayed but after a few second names displayed
