### ISSUE TITLE
Email Content Updates: Order Receipt email

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#66]
1. Order Receipt Email Content Changes

Everything else in this email remains same, except two sections:

a. Payment Information:

>For Cash on Delivery Service, we only accept Cash.
>
>If you choose to pick your order yourself, we accept Cash, American Express, Visa, Master Card etc at our Store. We also accept payments via online funds transfer to our bank account(s) to which you can submit the order payment (bank account details can be taken by calling us at our landline numbers).

b. Order Fulfillment Method:

>This order will be delivered within the next 24 hours (if placed before 3pm) from the time it is confirmed (we will send you an order confirmation email shortly after this order is placed). If your order is placed after 3 pm then it will be delivered within 48 hours of the confirmation email. If you need to get your order delivered the same day, please call our store numbers to process your request. For same day deliveries, delivery charges will apply (For details please call us at our landline number).
>
>The order will be delivered to the address given below:
>
>House No. XXX,
Street No. XXX,
Sector X-XX/X.
Islamabad-Pakistan.
0333-XXXXXXX
>
>Note: If you want to choose Self Pick Up at our store instead of Cash on Delivery (COD) you should call us at our landline numbers, within 2 hours of placing this order.

**Comment by uuaqarahmed** [comment]
@sabzesajee please update email content of Order receipt email

**Comment by sabzesajee** [comment]
@kamrannaqvi check please

**Comment by kamrannaqvi** [comment]
@sabzesajee 
1. The shipping address is showing two times in the order receipt email. so pls remove the following content from the  "Order Fulfilment" box in the email:

>The order will be delivered to the address given below: 
Imran Alpha
NEW Acme Inc.
123, acme street
acme ville, 44000
Pakistan
T: 786786786 

2 Remove the "shipping method" box in the email. It is empty.

**Comment by sabzesajee** [comment]
@kamrannaqvi  check please

**Comment by kamrannaqvi** [comment]
verified.
