### ISSUE TITLE
Email Content Updates: Order Confirmation email

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#67]
1 Everything else remains same, except:

>>> Exclude this text: 
The product (s) will be reserved for 12 hours, after that your order will be cancelled automatically. So you need to pick up your order within 12 hours after this confirmation. For any order related queries, please call at 051-2872041 and mention your Order-ID to the customer care representative.

And update it with: 

>The ordered item(s) will be delivered at your door step, within 24-48 hours from now. 
If you opted for Self Pickup from our store, you may now arrange to pick up your readied items from our store by mentioning your order-ID to the customer care representative.

2 Update the following sections of the email:

a. Payment Information:

>For Cash on Delivery Service, we will only accept Cash.
>
>If you selected to pick your order yourself, we will accept Cash, American Express, Visa, Master Card etc at our Store. We also accept payments via online funds transfer to our bank account(s) to which you can submit the order payment (bank account details can be taken by calling us at our landline numbers).

b. Order Fulfillment Method:

>This order will be delivered within the next 24-48 hours. If you need to get your order delivered the same day, please call our store numbers to process your request. For same day deliveries, delivery charges will apply (For details please call us at our landline number).
>
>The order will be delivered to the address given below:
>
>House No. XXX,
Street No. XXX,
Sector X-XX/X.
Islamabad-Pakistan.
0333-XXXXXXX

**Comment by uuaqarahmed** [comment]
@sabzesajee please update content of Order confirmation email

**Comment by sabzesajee** [comment]
@kamrannaqvi  check please

**Comment by kamrannaqvi** [comment]
@sabzesajee 
1. The shipping address is showing two times in the email. so pls remove the following content from the  "Order Fulfilment" box in the email:

>The order will be delivered to the address given below: 
Imran Alpha
NEW Acme Inc.
123, acme street
acme ville, 44000
Pakistan
T: 786786786 

2. Remove the "shipping method" box in the email. It is empty.

**Comment by kamrannaqvi** [comment]
verified.
