### ISSUE TITLE
Email Content Updates: Order Cancellation email

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#68]
Change content to:

>Esajee's
Shop # 9, Kohsar Market, F-6/3. Islamabad-Pakistan.
051-2872041
>
>Customer Name	
Street : H. no XXXX, Street XX, Sector X-XX/X. City : Islamabad Country: Pakistan, Pin Code : 44000	
T:0333-XXXXXXX
>
>Dear Customer Name,
>
>Reference to the order ID#100000200. Placed on Apr XX,XXXX has surprised us to notice your silence in response to our calls, at your given number.
>
>We therefore, have no other option but to cancel your order. We regret that we cannot process the delivery unless we don't get to hear from you over the phone call.
>
>We now request you to kindly treat your order, canceled.
>
>You can check the status of your order by logging into your account.
>
>If you have any questions, please feel free to contact us at esajee@esajeesolutions.com or by phone at 051-2872041.
>
>Thank you Esajee's

**Comment by uuaqarahmed** [comment]
@sabzesajee please change email content of order cancellation email

**Comment by sabzesajee** [comment]
@kamrannaqvi  check please

**Comment by kamrannaqvi** [comment]
verified.
