### ISSUE TITLE
Content Updates for: Checkout Steps (boxes and labels)

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#69]
1a. Change Step 1 label title to "Cash on Delivery"

1b. Change the content inside the step 1 box to:

>You will receive your order within 24-48 hours of our confirmation email. You will receive your ordered items at the address given below:
>
>	   House No. XXX,
>	   Street No. XX,
>	   Sector X-XX/X,
>	   Islamabad-Pakistan.
>	   0333-XXXXXXX
>
>Note: If you want to choose Self Pick Up from our store instead of Cash on Delivery (COD) you should call us at our landline numbers, right after placing your order.
>

1c. The address should be allowed to be edited by customer in this step. 

1d. Provide a button to [Save] any changes made to the shipping address.

2 Order Fulfillment Method (box content)

>This order will be delivered within the next 24 hours (if placed before 3pm) from the time it is confirmed (we will send you an order confirmation email shortly after this order is placed). If your order is placed after 3pm then it will be delivered within 48 hours. If you need to get your order delivered the same day, please call our store numbers to process your request.
>
>Note: For same day deliveries, delivery charges will apply.

3 Payment Information (box content)

>For Cash on Deivery Service, we only accept Cash.
>
>If you choose to pick your order yourself, we accept Cash, American Express, Visa, Master Card etc at our Store. We also accept payments via online funds transfer to our bank account(s) to which you can submit the order payment (bank account details can be taken by calling us at our landline numbers).

4 Order Review

>[Should remain the way it is at the moment].

**Comment by sabzesajee** [comment]
Done,

For 1b. there is a select list contain all the address of the customer with the option new address now if you want new address select new address, form will open for this option to enter new address and click on continue, the address will automatically save.

**Comment by kamrannaqvi** [comment]
1. It does not apply the new address as shipping address. i.e. billing address is sent in the order email to staff instead of the new shipping address added in step-1 by customer. For this phase the shipping address will be the billing address as well
2. It does not save any new address added in checkout step 1
3. In Payment Information box, pls. correct the spelling of "Delivery" in the first line

**Comment by sabzesajee** [comment]
All these are doneV

**Comment by kamrannaqvi** [comment]
There are few problems:

1. If I print the order from website (shown below) the new address that I put in while checking out shows as the "Billing Address" and the Shipping address remains the original address. In fact we need to change both of these addresses as for this phase we will only cater for the case that the shipping and billing addresses of COD orders will remain same.

![image](https://cloud.githubusercontent.com/assets/10416359/7173731/5b6e4c64-e415-11e4-8661-1c70d9cd3319.png)


2. Shipping Address section is empty. Please insert the cotent below:

This order will be delivered within the next 24 hours (if placed before 3pm) from the time it is confirmed (we will send you an order confirmation email shortly after this order is placed). If your order is placed after 3pm then it will be delivered within 48 hours. If you need to get your order delivered the same day, please call our store numbers to process your request.

Note: For same day deliveries, delivery charges will apply.

**Comment by sabzesajee** [comment]
Fixed

**Comment by kamrannaqvi** [comment]
The print order page is now ok. Please also change the "My Orders" page when a customer views the order details from their 'My Account' function. The changes are depicted below.

![image](https://cloud.githubusercontent.com/assets/10416359/7196034/5fa0fbaa-e4e3-11e4-99f2-21b9bbd465e0.png)

**Comment by sabzesajee** [comment]
Ok :)

**Comment by sabzesajee** [comment]
Done check @kamrannaqvi

**Comment by kamrannaqvi** [comment]
verified.
