### ISSUE TITLE
Special Order # 133

### ISSUE THREAD

**Issue by SiddiqueAhmad** [EsajeeSolutions/Esajeesite#7]
Special order form submission should initiate 2 emails:
a. one to customer to confirm the receipt of their order with order summary
b. to store for order processing

No action is currently taken except order saved in the special orders list in magento

**Comment by sabzesajee** [comment]
These are special order emails format
first to staff and the second is to customer
![to staff](https://cloud.githubusercontent.com/assets/6996232/5854143/7999dccc-a24c-11e4-8ecf-cb2845d1198f.jpg)
![to customer](https://cloud.githubusercontent.com/assets/6996232/5854144/79fee0cc-a24c-11e4-8495-d76e411220a7.jpg)

**Comment by kamrannaqvi** [comment]
The email templates for special orders were sent by email (jan 13). Pls. replace the above templates with the new ones below (refer to my email). 

1===>

![image](https://cloud.githubusercontent.com/assets/10416359/5895979/e40d8d56-a54e-11e4-9e39-fcd8dc6c3983.png)

2==>

![image](https://cloud.githubusercontent.com/assets/10416359/5895986/02c332f0-a54f-11e4-97b7-a93fe4b84778.png)

3==>

![image](https://cloud.githubusercontent.com/assets/10416359/5895993/1ec7aa6c-a54f-11e4-8042-fd2207c06490.png)

**Comment by sabzesajee** [comment]
Please explain from where and when 3rd email template will generate

**Comment by kamrannaqvi** [comment]
OK. So initially, the 3rd email can be sent manually by the dedicated staff handling online orders. The approval feature can be developed after release-1. We can 'suspend' this issue till further discussion.
