### ISSUE TITLE
Content updates for: Checkout Progress column on right side

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#70]
1 Cash on Delivery Address
	
	   House No. XXX,
	   Street No. XX,
	   Sector X-XX/X,
	   Islamabad-Pakistan.
	   0333-XXXXXXX

2 Order Fulfillment Method

>Cash On Delivery at your door step, within the allotted time in our order confirmation email.

3 Payment Information

>Cash on Delivery: Only Cash payment is accepted.
Self Pick Up Store: In Store, American Express, Visa, Master Cards or payments via online funds transfer to our bank account.

**Comment by sabzesajee** [comment]
Remove the previous steps and content and add these new steps??? please explain.

**Comment by thatshussnain** [comment]
Sabz, please remove the current Checkout Progress Steps/Content, and replace it with the above given new Content, as given by Mr. Kamran.

**Comment by kamrannaqvi** [comment]
The above content should display in the right hand side column titled "Checkout Progress" which appear when customer is checking out. Currently the column is displaying the text below:

===============================
CHECKOUT PROGRESS

1. Self Pick Up Store
Esajee's
Shop # 9, Kohsar Market, F-6/3. Islamabad-Pakistan.
051-2872041

2. Order Fulfilment Method
Customer self pickup from store - within 12 hours of order confirmation.

3. Payment Information
In store cash, American Express, Visa, Master cards or payments via online funds transfer to our bank account.
================================================= 

Pls. replace this text by the new one posted above in the issue. Let me know if any further clarification required.

**Comment by uuaqarahmed** [comment]
@sabzesajee please update this as well

**Comment by sabzesajee** [comment]
Done check Now

**Comment by kamrannaqvi** [comment]
verified.
