### ISSUE TITLE
Adjustment status of SKUs in magento

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#71]
Add a new field in SKU edit function in magento backend that should display the Adjusted/Not-adjusted status of that SKU. The adjustment status for each sku should also be visible in a column when viewing all SKUs list/catalog in magento. This feature should be available for all items in magento

**Comment by sabzesajee** [comment]
Done

**Comment by kamrannaqvi** [comment]
Please explain how to test this. 
Thanks.

**Comment by uuaqarahmed** [comment]
@sabzesajee please coordinate with siddique to display the data properly. At the moment 035000741264 is adjusted in kohsar but shows No in admin. Please fix this.

**Comment by SiddiqueAhmad** [comment]
Sabz you getting method name adjustments update isadjusted new col to 1 for this case

Also update price in all cases

**Comment by sabzesajee** [comment]
Done

**Comment by kamrannaqvi** [comment]
Need instructions to verify this.

**Comment by sabzesajee** [comment]
sir siddique will guide you

**Comment by sabzesajee** [comment]
@kamrannaqvi  check please and discus with sir @SiddiqueAhmad

**Comment by kamrannaqvi** [comment]
This and #43 needs to be verified together.

**Comment by uuaqarahmed** [comment]
@kamrannaqvi check 343160 (1 unit/Rs. 285), 043647410023 (5 units/Rs. 450) and 3073780624435 (20 units/Rs. 220) - All at the time of this message (values may change later)

**Comment by uuaqarahmed** [comment]
@sabzesajee please change No to Yes when adjusted, currently the process is updating both price and stocks but No is not changed to Yes

**Comment by kamrannaqvi** [comment]
Price and quantity matches SCM vs. Magento but adjustment status is not updated in magento. 
Couldn't login to POS to verify at pos side.

**Comment by SiddiqueAhmad** [comment]
@uuaqarahmed adjustment status is updated, search with adjusted = 1 from website side, showing around 100+ item adjusted w.r.t website items

**Comment by uuaqarahmed** [comment]
@kamrannaqvi please check and confirm

**Comment by kamrannaqvi** [comment]
The filter by Adjusted/Non-Adjusted in magento is not showing correct results. There are over 13800 items in total, out of which it shows 2241 items as 'adjusted' (if we enter '1' in filter and search) and 1171 items as 'not-adjusted' (enter '0' in filter and search). These number do not add up to make 13800 items. 

This test can only cover magento side verification.

**Comment by uuaqarahmed** [comment]
@sabzesajee please check items that are neither 0 nor 1

**Comment by kamrannaqvi** [comment]
Also the live SCM shows 8750 items as Adjusted, while only 2241 items are displayed as Adjusted in Magento. Sync issue needs to be resolved.

![image](https://cloud.githubusercontent.com/assets/10416359/7449435/f0b88a12-f24f-11e4-8f87-2a4c2fdb657c.png)

![image](https://cloud.githubusercontent.com/assets/10416359/7449438/14e83bbc-f250-11e4-93f9-f8f00e42bb24.png)

**Comment by SiddiqueAhmad** [comment]
@uuaqarahmed job scheduled for update all items regardless of enabled or not

**Comment by kamrannaqvi** [comment]
Both problems reported above still exist. Not resolved.

**Comment by uuaqarahmed** [comment]
@SiddiqueAhmad can you please check whether the sync process ran successfully or not

**Comment by SiddiqueAhmad** [comment]
@uuaqarahmed job completed, and now total adjusted is around 9000
@sabzesajee check why total items is not equal to adjusted + non adjusted (mean there are 1000 items have neither value 1 or 0 )

**Comment by sabzesajee** [comment]
Yes because these products are created before we add this new field so its
value is null.
Now i have changed the value if it is neither 1 or 0 then the column will
show "not updated yet"
Now tell me further action what to do with these products?

**Comment by SiddiqueAhmad** [comment]
@sabzesajee easy go, just make them not adjusted,

**Comment by sabzesajee** [comment]
Done.

There are about 620 products having is adjusted is null if you want to
update this to 0 or 1 from database then tell me i can update these through
script.

**Comment by sabzesajee** [comment]
I have updated null to 0.

On Thu, May 14, 2015 at 12:04 AM, Ali Khan <alisoftwareengineerphp@gmail.com

**Comment by kamrannaqvi** [comment]
1. There are now 2 statuses representing the not-adjusted status (i.e. "No" and "Not Adjusted"). This should be changed to just "No" for all not-adjusted items

![image](https://cloud.githubusercontent.com/assets/10416359/7628061/cfef3d2c-fa37-11e4-94ba-091977a99e8b.png)


2. There are still more than 400 items in magento without a 0 or 1 status.

**Comment by SiddiqueAhmad** [comment]
@sabzesajee any update on this ?

**Comment by sabzesajee** [comment]
check this now

**Comment by kamrannaqvi** [comment]
1- resolved
2- not resolved (512 items in magento without a 0 or 1 status)

**Comment by SiddiqueAhmad** [comment]
@kamrannaqvi two resolved, now both match

**Comment by kamrannaqvi** [comment]
verified.
