### ISSUE TITLE
Update Content of Graphic Banner on Landing Page of Esajee Website

### ISSUE THREAD

**Issue by thatshussnain** [EsajeeSolutions/Esajeesite#77]
Dear Valued Customers,
 
Now at Esajee's, you can order online from the comfort of 'wherever-you-are', and get your order delivered at your doorstep. You can also choose Self Pick Up from our Esajee's Kohsar Market store.
 
All you need to do is:
 
> Sign up for free at Esajee's Online store.
> Shop all your favorite products online.
> Complete the simple checkout procedure.
> Receive an Order Confirmation email with all the required details.
> The Order can be delivered as Cash on Delivery and as Self Pick Up from Store (Choose your convenience).
 
Enjoy the new experience at Esajee's!

**Comment by uuaqarahmed** [comment]
@sabzesajee it is design related and you don't need to do anything

**Comment by uuaqarahmed** [comment]
@sabzesajee  please use attached banner. 

![banner08](https://cloud.githubusercontent.com/assets/527591/7224091/d7e4256e-e746-11e4-9e0e-4e5698bc3761.png)

**Comment by sabzesajee** [comment]
@uuaqarahmed  updated

**Comment by uuaqarahmed** [comment]
@kamrannaqvi plz verify

**Comment by kamrannaqvi** [comment]
verified.

**Comment by kamrannaqvi** [comment]
Old banner for record.

![image](https://cloud.githubusercontent.com/assets/10416359/7229798/24c786fc-e781-11e4-8536-1fe9c47ad510.png)

**Comment by thatshussnain** [comment]
@sabzesajee : This issue was resolved, but, when I logged in from another PC today and opened esajee's website, so, instead of new banner, old banner was being displayed. Please check!

I have attached the screen shot etc.
![graphic banner](https://cloud.githubusercontent.com/assets/11936534/7231819/43d1c98a-e791-11e4-9385-2f0a8bb6bd95.jpg)

**Comment by thatshussnain** [comment]
Resolved. Verified.
