### ISSUE TITLE
Replace the Christmas with "Complement your sweet tooth"

### ISSUE THREAD

**Issue by thatshussnain** [EsajeeSolutions/Esajeesite#78]
On the landing page, there is a Christmas carousel. We need to replace the Text "Christmas" with "Complement your sweet tooth".

Pls see attached screenshot for reference.
![untitled](https://cloud.githubusercontent.com/assets/11936534/7174144/210b34d6-e41c-11e4-8fb2-778bef11ff12.jpg)

**Comment by sabzesajee** [comment]
@thatshussnain  check please

**Comment by thatshussnain** [comment]
@sabzesajee : Resolved.
