### ISSUE TITLE
set alignment # 132

### ISSUE THREAD

**Issue by SiddiqueAhmad** [EsajeeSolutions/Esajeesite#8]
The following blocks are misaligned and slips over the borders:

My Account>My Dashboard>Account information (heading + text =not aligned)
My Account>Address Book>Default Addresses (heading + boxes =not aligned)
My Account>My Orders>click View Order>shipping/billing Address (heading + boxes =not aligned)

**Comment by sabzesajee** [comment]
issue fixed on local

**Comment by kamrannaqvi** [comment]
last 2 parts of the issue not fixed:

My Account>Address Book>"Default Addresses" heading =not aligned. Inside and outside box borders (left) overlap each other.

My Account>My Orders>click View Order>shipping/billing Address (see boxes' left borders  and inside text overlaps)

**Comment by sabzesajee** [comment]
Fixed, Check now

**Comment by kamrannaqvi** [comment]
Verified fixed.
