### ISSUE TITLE
The order email generated when an online order is submitted should be CCed to a few concerned people.

### ISSUE THREAD

**Issue by thatshussnain** [EsajeeSolutions/Esajeesite#81]
The order email generated, when an online order is submitted should be CCed to: Hussnain, Hunaid Shb, Hasnain Shb, Waqar Shb, Kamran Shb.

**Comment by uuaqarahmed** [comment]
@sabzesajee if there is a way to add this from the admin then please mention process otherwise add email addresses of these users

**Comment by sabzesajee** [comment]
@thatshussnain you can add this from backend. steps are:

Go to system>configuaration>sales> sales email
and then see for the order tab search for "Send Order Email Copy To" here you can add emails

**Comment by thatshussnain** [comment]
@sabzesajee : Thanks. Email Id's added.
