### ISSUE TITLE
Log Outs from the website automatically.

### ISSUE THREAD

**Issue by thatshussnain** [EsajeeSolutions/Esajeesite#82]
When a user logs in to the website, and click upon HOME or Health & Beauty etc, when the page loads and appears, the user is automatically logged out from the session.

The button at the above right corner shows as "Log In".

User automatically logs out from the page, which should not happen in the normal case.

Please Check!

**Comment by thatshussnain** [comment]
Currently it is working fine, I will keep testing for a day, just to be sure.

**Comment by sabzesajee** [comment]
its look server issue

**Comment by thatshussnain** [comment]
Working Fine.
