### ISSUE TITLE
Add new text on website sections and emails

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#87]
Add in policy, terms and other relevant sections of the website and also in the emails sent to to customer after ordering, the text: 
“Perishable items will only be delivered to certain areas only” 
@thatshussnain: pls. tell sabz where to add this exactly.

**Comment by thatshussnain** [comment]
@kamrannaqvi : Text added to the pages it was required to be added. e.g. Shipping Options, Customer Service etc
