### ISSUE TITLE
Prepare the frontend for launch

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#88]
Pls. Prepare the frontend and remove any testing traces and complete other prep tasks:

- Add items in Empty categories
- Add items in pages that open empty when any banner or logo is clicked on the main page
- Add items in pages that open empty when any link or menu item is clicked 
- Do a thorough launch ready usability test
- The order email generated when an online order is submitted should be CCed to kamran, waqar, hussnain, hunaid, hasnain sb

Hussnain: Add more preparatory tasks to the list above.

**Comment by thatshussnain** [comment]
1. I have added items to Empty Categories (Except BAGEL, because none adjusted product is available at back end)
2. Resolved.
3. Resolved.
4. Tested. (Saw an issue, which has been reported)
5. All Email Ids have been added to Order Email Generated for Online Order.
