### ISSUE TITLE
Hide CC options from the checkout process

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#89]
For the website launch on tuesday (26-5-15), please hide the credit card options displayed during the checkout process step no. 3, as it is not fully functional as of now. 
This option will be added later when we have integrated and tested the mcb gateway successfully.

@SiddiqueAhmad Pls correct me if wrong.

**Comment by sabzesajee** [comment]
Done cc methods are hide
