### ISSUE TITLE
stock updates # 107

### ISSUE THREAD

**Issue by SiddiqueAhmad** [EsajeeSolutions/Esajeesite#9]
Make service to manage the stock updates, we will post you changes on stock, and you need to create service to consume that

==========================

Get stock tally updated 
a. [Waqar]: For this release we will pull current enabled items from DB in excel and email the store for tally and stock quantity update. we can then enable/disabled available/out of stock items
b. For later release, ask owners/mgmt to get the stock tally process implemented and updated 100% for the entire products DB/inventory and stocks manager should keep inventory tally up to date regularly so only available item display on website always

**Comment by sabzesajee** [comment]
To update magento stock please call this link
http://esajeecom.esajee.com/quickstart/index.php/links/index/stockupdate?sku=3232323&qty=111
