### ISSUE TITLE
Page Title Issue.

### ISSUE THREAD

**Issue by thatshussnain** [EsajeeSolutions/Esajeesite#90]
I have added some new products to site today. The new products that I have added, all show page title as "Product meta title" while all old products already available show correct titles. I have tried quite a few times, to change it from backend magento, but, unfortunately, I couldn't.

Please see attached two images:

1. Is with correct title
2. Is with wrong title.

Please check what is the issue?
![correct](https://cloud.githubusercontent.com/assets/11936534/7767243/4074cee2-008a-11e5-896c-939c59f7b4f4.jpg)
![wrong](https://cloud.githubusercontent.com/assets/11936534/7767247/46c14230-008a-11e5-976a-5049486f7276.jpg)

**Comment by SiddiqueAhmad** [comment]
@thatshussnain for this i changed the title of Hershey's Kisses Chocolate 240 g, you need to select use default values in edit

**Comment by thatshussnain** [comment]
Resolved.
