### ISSUE TITLE
Magento admin not logging in

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#93]
Magento admin backend for the new site, I cannot login as admin. The login page keeps reloading without any error

**Comment by sabzesajee** [comment]
check Now

**Comment by sabzesajee** [comment]
if not then please delete browser cache

On Thu, May 28, 2015 at 11:22 AM, Ali Khan <alisoftwareengineerphp@gmail.com

**Comment by kamrannaqvi** [comment]
@sabzesajee Its not working after cache clearing, using different browser even. The URLs linked with the images are static you will have to change them all manually. 
Where else could this issue occur?

**Comment by sabzesajee** [comment]
by the its working with me i am logged in with with admin/admin123

**Comment by uuaqarahmed** [comment]
@sabzesajee plz mention login url

**Comment by sabzesajee** [comment]
![untitled](https://cloud.githubusercontent.com/assets/6996232/7855528/d982cd9a-053b-11e5-9c4b-a8552ddedc06.jpg)




URl : http://www.esajee.com/index.php/admin

**Comment by uuaqarahmed** [comment]
@sabzesajee its working but very slow and takes forever to load the dashboard

**Comment by sabzesajee** [comment]
and also its working fine with speed loading every thing is ok

**Comment by uuaqarahmed** [comment]
@kamrannaqvi can you check?

**Comment by kamrannaqvi** [comment]
@uuaqarahmed aoa good to see you back :)
@sabzesajee I can log in but just like Waqar sb mentioned it takes too long to load after login screen. I entered my user/pass 7 mins ago and it is still loading the Dashboard page

**Comment by uuaqarahmed** [comment]
@kamrannaqvi was thanks. I have noticed that it takes a lot of time to load on first login attempt but if we stop page load and refresh, it starts working. Can you check this?

**Comment by kamrannaqvi** [comment]
Yes same happens in my observation

**Comment by sabzesajee** [comment]
I tried to trace this issue but don't what is reason as in my office its working very fine and speed is good but on my 3G net its slow.
