### ISSUE TITLE
Images are not routing it to the actual pages, they all route/navigate to Homepage after being live

### ISSUE THREAD

**Issue by thatshussnain** [EsajeeSolutions/Esajeesite#94]
The banners/links/images/logos available on website, they all route/navigate to Homepage after the website is gone live. Before that, they all were working perfectly fine.

Please see attached screen shots, which need to be resolved.
![1 and 2](https://cloud.githubusercontent.com/assets/11936534/7853555/6d5e3b16-0529-11e5-9ee9-137447e7edb9.jpg)
![3](https://cloud.githubusercontent.com/assets/11936534/7853556/6d60343e-0529-11e5-9e49-6ef13188b0f1.jpg)
![4](https://cloud.githubusercontent.com/assets/11936534/7853557/6d63bff0-0529-11e5-932e-5e60b47aaa64.jpg)
![5-6-7-8](https://cloud.githubusercontent.com/assets/11936534/7853558/6d642e68-0529-11e5-8904-5bd2cbc59bf2.jpg)

**Comment by sabzesajee** [comment]
@SiddiqueAhmad  @kamrannaqvi  Done

**Comment by thatshussnain** [comment]
@sabzesajee : Resolved.
