### ISSUE TITLE
web service for image

### ISSUE THREAD

**Issue by SiddiqueAhmad** [EsajeeSolutions/Esajeesite#98]
make one web service, and if we call it with barcode, it should return image url of that products

**Comment by sabzesajee** [comment]
@SiddiqueAhmad Done.
The link is http://www.esajeecom.esajee.com/index.php/links/index/productimage?barcode=869050455636755

**Comment by SiddiqueAhmad** [comment]
@sabzesajee can you push code changes

**Comment by sabzesajee** [comment]
Okay

**Comment by SiddiqueAhmad** [comment]
@sabzesajee please live it

**Comment by sabzesajee** [comment]
@SiddiqueAhmad done now on live site
